[build]
  command = "npm ci && npx prisma generate && npm run build"
  publish = ".next"
  node_version = "20.10.0"

[build.environment]
  NODE_VERSION = "20.10.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-audit --no-fund"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Dummy keys for build time
  OPENAI_API_KEY = "sk_dummy_key_for_netlify_build_only"
  STRIPE_SECRET_KEY = "sk_test_dummy_key_for_netlify_build_only"
  STRIPE_WEBHOOK_SECRET = "whsec_dummy_key_for_netlify_build_only"
  DATABASE_URL = "postgresql://dummy:dummy@localhost:5432/dummy"
  GOOGLE_CLIENT_ID = "dummy_client_id"
  GOOGLE_CLIENT_SECRET = "dummy_client_secret"
  NEXTAUTH_SECRET = "dummy_nextauth_secret"
  NEXTAUTH_URL = "https://dummy-url.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functionsDirectory]
  "*" = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 