[build]
  command = "npm ci && npx prisma generate && npm run build"
  publish = ".next"
  node_version = "20.10.0"

[build.environment]
  NODE_VERSION = "20.10.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-audit --no-fund"
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_SKIP_LINT = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Required environment variables
  DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/immigration_helper"
  STRIPE_SECRET_KEY = "sk_test_placeholder"
  STRIPE_WEBHOOK_SECRET = "whsec_placeholder"
  GOOGLE_CLIENT_ID = "placeholder"
  GOOGLE_CLIENT_SECRET = "placeholder"
  NEXTAUTH_SECRET = "immigration-helper-ai-secret-key"
  NEXTAUTH_URL = "https://teal-pony-71653a.netlify.app"
  OPENAI_API_KEY = "sk_dummy_key_for_netlify_build_only"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functionsDirectory]
  "*" = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 