[build]
  command = "npm ci && npm run netlify-build"
  publish = "dist"
  node_version = "20.10.0"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--legacy-peer-deps"
  # Static export mode
  NEXT_STATIC_EXPORT = "true"
  # Disable TypeScript checks
  NEXT_SKIP_TYPE_CHECK = "1"
  NEXT_SKIP_LINT = "1"
  NEXT_TELEMETRY_DISABLED = "1"
  # Dummy key for build time
  OPENAI_API_KEY = "sk_dummy_key_for_netlify_build_only"
  # Increase Node.js memory
  NODE_OPTIONS = "--max_old_space_size=4096"
  # Set build environment
  NODE_ENV = "production"

# Remove the Next.js plugin since we're using static export

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 