[build]
  command = "npm ci && npm run build"
  publish = ".next"
  node_version = "20.10.0"

[build.environment]
  NODE_VERSION = "20.10.0"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-audit --no-fund"
  NEXT_SKIP_TYPE_CHECK = "true"
  NEXT_SKIP_LINT = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Dummy key for build time
  OPENAI_API_KEY = "sk_dummy_key_for_netlify_build_only"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functionsDirectory]
  "*" = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 