[build]
  command = "npm install dotenv && npx prisma generate && npm run netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  # Provide dummy key for build time to prevent errors - will be overridden by real key in Netlify environment variables
  OPENAI_API_KEY = "sk_dummy_key_for_netlify_build_only_will_be_replaced_in_production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 